// import {

//   Link
// } from "react-router-dom";
import Menu from "./../components/menu/Menu";
import Header from "./header/Header";
import Head from 'next/head'
import styles from "./styleContent.module.css";

const contentClass = {
  alignItems: "center",
  width: "1200px",
  margin: "auto",
};

const mainClass = {
  width: "1200px",
  display: "flex",
  flexDirection: "row",
};

const menuClass = {
  width: "245px",
  padding: "0px 5px 0px 0px",
};

function ContentBox({ content="", children, ...params }) {
  let className = styles.boxContent;
  if (params.hideBorder) { 
    className += " "+ styles.boxContentHide;
  }

  
  const getHead = () => {
    let result = "";
    if (params.ticker || params.title) {
      result = (
        <div className={styles.titleClass}>
          <h2>
            {" "}
            {params.ticker ? params.ticker + " : " : ""} {params.title}
          </h2>
        </div>
      );
    }
    return result;
  };

  return (
    <div>
        <Head>
            <title>title  ContentBox </title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
      <div className={styles.headerClass}>
        <Header />
      </div>
      <div style={contentClass}>
        <div style={mainClass}>
          <div style={menuClass}>
            <Menu />
            <div className={styles.blockHr}></div>
          </div>
          <div className={styles.mainContent}>
            {getHead()}
            <div className={className}>
              {children}
            </div>
          </div>
        </div>
      </div>

      <div className={styles.footer}>
        <div className={styles.footerContent}>
        footer
          
        </div>
      </div>
    </div>
  );
}

export default ContentBox;
