import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import ContentBox from "../components/ContentBox";
import { getServerSession} from "next-auth";
import { loadEnvConfig } from '@next/env'
import { useSession, getSession } from "next-auth/react"

const inter = Inter({ subsets: ['latin'] })

export default function Home(req:any, res:any) {
  const { data: session, status } = useSession()
  
  //const projectDir = process.cwd()
 // loadEnvConfig(projectDir)
//  if (status === "loading") {
//   return <p>Loading...</p>
// }

// if (status === "unauthenticated") {
//   return <p>Access Denied</p>
// }
console.log('status',status);

 
  return (
    <>
      <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
            {/* <script src="./datepicker/datepicker.min.js"></script> */}
            {/* <script src="./datepicker/datepicker.min.css"></script> */}
      </Head> 

  
        <ContentBox  hideBorder={true}  pageTitle={"BoxInvesting - анализ инструментов, акций для инвестирования"}>
          


        </ContentBox>
    </>
  )
}


